### PR TITLE
Try triggering CI using comment

### PR DESCRIPTION
**Pull request by sadanand48**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## What is the link to the Apache JIRA

(Please create an issue in ASF JIRA before opening a pull request,
and you need to set the title of the pull request which starts with
the corresponding JIRA issue number. (e.g. HDDS-XXXX. Fix a typo in YYY.)

Please replace this section with the link to the Apache JIRA)

## How was this patch tested?

(Please explain how this patch was tested. Ex: unit tests, manual tests)
(If this patch involves UI changes, please attach a screen-shot; otherwise, remove this)

### CODE REVIEW

**Comment by sadanand48** [comment]
sample comment

**Comment by mukul1987** [comment]
@sadanand48 does this patch work ?

**Comment by sadanand48** [comment]
@mukul1987 No. Was just trying out if this is possible. I  found out that we cant re-trigger PR checks via issue_comment .  Workflows that are triggered via comments always run on a default branch and not a specific ref.

> Status check  is for a specfic ref. But issue_comment event is not related to a specific ref, it always use Default Branch. It will not show on PR Checks tab

https://github.community/t/on-issue-comment-events-are-not-triggering-workflows/16784/4

**Pull request merged**
